mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 192.168.1.3
    port: 1883
    keepalive: 60
  private_path: device/001
serializer: msgpack:dumps
deserializer: msgpack:loads
bridge:
  # receive data
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: sensor_msgs.msg:LaserScan
    topic_from: /ros/ktbot0/laser_scan
    topic_to: laser_scan
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: /ros/ktbot0/odom
    topic_to: odom
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: tf.msg:tfMessage
    topic_from: /ros/ktbot0/tf
    topic_to: /tf
  # publish commands
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: geometry_msgs.msg:Twist
    topic_from: cmd_vel
    topic_to: /ros/ktbot0/cmd_vel
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: set_spin
    topic_to: /ros/ktbot0/set_spin
