<?xml version="1.0"?>
<robot name="lx_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="base_width" value="0.077" /> <!-- Square dimensions (widthxwidth) of base -->
  <xacro:property name="base_height" value="0.03" /> <!-- Base height --> 
  <xacro:property name="conn_to_axle" value="0.0335" /> <!-- Length from attach point to axle --> 
  <xacro:property name="servo_height" value="0.045" /> <!-- Height of servo -->
  <xacro:property name="servo_to_axle" value="0.0385" /> <!-- Length from base of servo to axle -->
  <xacro:property name="servotop_to_axle" value="${servo_height - servo_to_axle}" />
  <xacro:property name="smallcon" value="0.0065" /> <!-- Extra spacing due to small connector -->
  <xacro:property name="servo_depth" value="0.0352" /> <!-- Depth of servo motor -->
  <xacro:property name="servo_width" value="0.025" /> <!-- Width of servo motor -->
  
  <xacro:property name="servo_inertial">
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${mass / 12.0 * (base_width*base_width + base_width*base_width)}"/>
    </inertial>
  </xacro:property>


  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find lx_arm)/src/lx_arm.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find lx_arm)/src/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>
  
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <xacro:insert_block name="servo_inertial"/>
  </link>

  <joint name="joint1" type="revolute">
    <limit effort="1000.0" lower="-${PI*0.6}" upper="${PI*0.6}" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0 0 ${base_height + conn_to_axle - servotop_to_axle}"/>
    <parent link="base_link"/>
    <child link="link1"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="0 0 ${-servo_height/2 + conn_to_axle}" rpy="0 0 0"/>
      <geometry>
        <box size="${servo_width} ${servo_depth} ${servo_height}"/>
      </geometry>
      <material name="dgrey"/>
    </visual>
  </link>

  <joint name="joint2" type="revolute">
    <limit effort="1000.0" lower="-${PI*0.6}" upper="${PI*0.6}" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0 0 ${servo_to_axle + conn_to_axle}"/>
    <parent link="link1"/>
    <child link="link2"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 ${-servo_height/2 + conn_to_axle}" rpy="0 0 ${PI/2}"/>
      <geometry>
        <box size="${servo_width} ${servo_depth} ${servo_height}"/>
      </geometry>
      <material name="dgrey"/>
    </visual>
  </link>

  <joint name="joint3" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${servo_to_axle + 2*smallcon + servo_to_axle}"/>
    <parent link="link2"/>
    <child link="link3"/>
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="0 0 ${servo_height/2 - conn_to_axle}" rpy="0 0 ${PI/2}"/>
      <geometry>
        <box size="${servo_width} ${servo_depth} ${servo_height}"/>
      </geometry>
      <material name="dgrey"/>
    </visual>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>