version: '2.3'
services:
    ktbot:
        extends:
            file: docker-compose.gpu.yml
            service: gpu
        container_name: ros2
        volumes:
            - ./ktbot:/catkin_ws
        image: ros:ktbot
    inserter:
        extends:
            file: docker-compose.gpu.yml
            service: gpu
        container_name: ros2
        volumes:
            - ./inserter:/catkin_ws
        image: ros:ktbot
    ros2:
        extends:
            file: docker-compose.gpu.yml
            service: gpu
        container_name: ros2
        volumes:
            - ./ktbot/ws:/ws
        image: osrf/ros2:nightly
    tf:
        extends:
            file: docker-compose.gpu.yml
            service: gpu
        container_name: tensorflow-1.13.1
        volumes:
            - /tmp/tf:/tf
        image: tensorflow/tensorflow:1.13.1-gpu
    gz:
        extends:
            file: docker-compose.gpu.yml
            service: gpu
        container_name: gazebo9
        volumes:
            - /tmp/tf:/tf
        image: gazebo:gzserver9
    id-pose:
        extends:
            file: docker-compose.gpu.yml
            service: gpu
        container_name: pose-estimation
        volumes:
            - ./inserter_detector/ws:/ws
        image: inserter-detector:pose-estimation
