version: '2.3'
services:
    gpu:
        restart: 'no'
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /tmp/.docker.xauth:/tmp/.docker.xauth
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}graphics
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=${XAUTH}
