mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 192.168.1.3
    port: 1883
    keepalive: 60
  private_path: device/001
serializer: msgpack:dumps
deserializer: msgpack:loads
bridge:
  # publish sensor data
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:LaserScan
    topic_from: laser_scan
    topic_to: /ros/ktbot0/laser_scan
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: wheel_diff_drive_controller/odom
    topic_to: /ros/ktbot0/odom
  # receive commands
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: geometry_msgs.msg:Twist
    topic_from: /ros/ktbot0/cmd_vel
    topic_to: wheel_diff_drive_controller/cmd_vel
