local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  origin_x: 3.0
  origin_y: 3.0
  expected_update_rate: 2.5
  resolution: 0.1
