# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint5
    - joint6
  constraints:
    stopped_velocity_tolerance: 0.01
  stop_trajectory_duration: 0.5
  state_publish_rate:  30
  action_monitor_rate: 10
  gains:
    joint1:
      p: 100.0
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint2:
      p: 100.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint3:
      p: 100.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint5:
      p: 100.0
      i: 0.01
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    joint6:
      p: 100.0
      i: 0.01
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
