<?xml version='1.0'?>
<robot name="arb" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find arb_description)/urdf/arb.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find arb_description)/urdf/materials.xacro" />

  <xacro:property name="INF" value="1.0e+50"/>
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="HEIGHT" value="0.6"/>
  <xacro:property name="FOREARM" value="0.3"/>

  <xacro:macro name="servo" params="suffix">
    <link name="servo_${suffix}">
      <inertial>
        <mass value="0.052"/>
        <inertia ixx="8.02e-06" ixy="0" ixz="0" iyy="1.188e-05" iyz="0" izz="1.448e-05"/>
      </inertial>
      <visual name='visual'>
        <geometry>
          <box size="0.035 0.025 0.046"/>
        </geometry>
        <material name="dgrey"/>
      </visual>
      <collision name='collision'>
        <geometry>
          <box size="0.035 0.025 0.046"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- <origin xyz="0.000537 0.007761 0.214993" rpy="0 0 0"/> -->

  <link name='base_link'>
    <inertial>
      <mass value="0.41"/>
      <inertia ixx="0.00076912" ixy="0" ixz="0" iyy="0.00062306" iyz="0" izz="0.00139144"/>
    </inertial>
    <visual name='visual'>
      <geometry>
        <box size="0.2 0.2 0.0033"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision name='collision'>
      <geometry>
        <box size="0.2 0.2 0.0033"/>
      </geometry>
    </collision>
  </link>

  <link name='spine'>
    <inertial>
      <mass value="0.41"/>
      <inertia ixx="0.00076912" ixy="0" ixz="0" iyy="0.00062306" iyz="0" izz="0.00139144"/>
    </inertial>
    <visual name='visual'>
      <geometry>
        <box size="0.02 0.02 ${HEIGHT}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision name='collision'>
      <geometry>
        <box size="0.02 0.02 ${HEIGHT}"/>
      </geometry>
    </collision>
  </link>
  <joint name="spine_to_base" type="fixed">
    <origin xyz="0 0 0.3" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="spine"/>
  </joint>


  <xacro:servo suffix='1'>
  </xacro:servo>
  <joint name='z_axis' type='prismatic'>
    <axis xyz="0 0 1"/>
    <limit lower="0.03" upper="0.56" effort="10" velocity="0.2"/>
    <origin xyz="0.025 0 ${-HEIGHT/2}" rpy="0 0 0"/>
    <parent link="spine"/>
    <child link="servo_1"/>
  </joint>

  <link name='upper_arm'>
    <inertial>
      <mass value="0.41"/>
      <inertia ixx="0.00076912" ixy="0" ixz="0" iyy="0.00062306" iyz="0" izz="0.00139144"/>
      <origin xyz="${FOREARM/2} 0 0"/>
    </inertial>
    <visual name='visual'>
      <geometry>
        <box size="${FOREARM} 0.02 0.02"/>
      </geometry>
      <material name="white"/>
      <origin xyz="${FOREARM/2} 0 0"/>
    </visual>
    <collision name='collision'>
      <geometry>
        <box size="${FOREARM} 0.02 0.02"/>
      </geometry>
      <origin xyz="${FOREARM/2} 0 0"/>
    </collision>
  </link>
  <joint name="shoulder" type="revolute">
    <axis xyz="0 0 1"/>
    <limit lower="-1.8" upper="1.8" effort="10" velocity="0.2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="servo_1"/>
    <child link="upper_arm"/>
  </joint>

  <link name='forearm'>
    <inertial>
      <mass value="0.41"/>
      <inertia ixx="0.00076912" ixy="0" ixz="0" iyy="0.00062306" iyz="0" izz="0.00139144"/>
      <origin xyz="${FOREARM/2} 0 0"/>
    </inertial>
    <visual name='visual'>
      <geometry>
        <box size="${FOREARM} 0.02 0.02"/>
      </geometry>
      <material name="white"/>
      <origin xyz="${FOREARM/2} 0 0"/>
    </visual>
    <collision name='collision'>
      <geometry>
        <box size="${FOREARM} 0.02 0.02"/>
      </geometry>
      <origin xyz="${FOREARM/2} 0 0"/>
    </collision>
  </link>
  <joint name="elbow" type="revolute">
    <axis xyz="0 0 1"/>
    <limit lower="-3.0" upper="3.0" effort="10" velocity="0.2"/>
    <origin xyz="${FOREARM} 0 0" rpy="0 0 0"/>
    <parent link="upper_arm"/>
    <child link="forearm"/>
  </joint>

</robot>
